### ISSUE TITLE
Cannot access AWS credentials via instance metadata

### ISSUE THREAD

**Issue by koterpillar** [fpco/cache-s3#14] opened 2019-01-07 23:58 UTC
`cache-s3` version `0.1.6` cannot access the AWS credentials if running on an EC2 instance with credentials provided via the metadata endpoint.

Here is a (redacted) log:

```
# aws sts get-caller-identity
{
    "Account": "xxxx",
    "UserId": "XXXX",
    "Arn": "arn:aws:sts::xxxx:assumed-role/xxxx/i-xxxx"
}
# curl http://169.254.169.254/latest/meta-data/
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
events/
hostname
iam/
instance-action
instance-id
instance-type
local-hostname
local-ipv4
mac
metrics/
network/
placement/
profile
reservation-id
security-groups
services/
# curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
xxxx-role
# cache-s3 --prefix xxxx restore stack
cache-s3: MissingFileError "/var/lib/xxxx/.aws/credentials"
```

**Comment by lehins** [comment] 2019-01-08 00:07
Strange, I was able to use it on an EC2 before with no problem, since credentials discovery is handled by amazonka, `cache-s3` does nothing special about it. 

Is it possible that ec2 instance profile isn't setup to have access to the s3 bucket? That could trigger such an error. Try using `aws-cli` from an instance to write some files into the bucket as a way to debug it.

Here is some terraform I use to setup proper AWS profile: https://gist.github.com/lehins/56968dd1a23dbc730e8755eea5475179

Let me know if it helps.

**Comment by lehins** [comment] 2019-01-08 00:12
Oh yea, I noticed that gist had outdated links, so I updated it. Here is the terraform that specifies the actual s3 policy: https://github.com/fpco/terraform-aws-foundation/blob/master/modules/s3-full-access-policy/main.tf

**Comment by koterpillar** [comment] 2019-01-08 00:24
Unfortunately that's not it, I can upload a file via `aws s3 cp` but `cache-s3` still gives me this error.

**Comment by lehins** [comment] 2019-01-08 00:35
Alright, I think that might be it: brendanhay/amazonka#271
Try:
```shell
$ curl http://instance-data/latest/meta-data/
```

**Comment by lehins** [comment] 2020-02-03 15:56
This is a confirmed issue with amazonka directly, so closing.

**Closed as completed by lehins** 2020-02-03 15:56 UTC
