### ISSUE TITLE
Permission denied error during save on Windows

### ISSUE THREAD

**Issue by wagdav** [fpco/cache-s3#23] opened 2019-04-16 13:12 UTC
This problem was introduced in 0.1.8. (0.1.7 was fine) and only affects Windows. I could reproduce this on:
* Windows 2016 (AMI provided by AWS)
* Windows 10 Vagrant box.

It enough to invoke the `save` command to trigger this error:

```
> cache-s3 --prefix=cache-s3-test save --relative-path clcache
[cache-s3][Info ][Tue, 16 Apr 2019 12:58:20 UTC]: Caching: clcache
[cache-s3][Info ][Tue, 16 Apr 2019 12:58:44 UTC]: <master.cache> - No previously stored cache was found.
[cache-s3][Info ][Tue, 16 Apr 2019 12:58:44 UTC]: <master.cache> - Data change detected, caching 308.3 MiB with sha256: bNlkj0BqEBs8JBa8flvruMvhjpIgkE6LdD5q9F49quM=
cache-s3: C:\Users\vagrant\AppData\Local\Temp\cache-s3.tar7484-0.gzip: DeleteFile "\\\\?\\C:\\Users\\vagrant\\AppData\\Local\\Temp\\cache-s3.tar7484-0.gzip": permission denied (Access is denied.)
```

The error message displays `\\?\` characters in the PATH, this suggests some Win32 path compatibility quirk.

Looks very similar to "Case 5" documented here: https://support.microsoft.com/en-us/help/320081/you-cannot-delete-a-file-or-a-folder-on-an-ntfs-file-system-volume

**Comment by lehins** [comment] 2019-04-16 14:44
@wagdav I am pretty sure this issue is due to temporary-resourcet package (or improper usage thereof), but instead of digging into it I'd rather switch to the package that I know will work for sure.
Could you confirm this issue is fixed in [`permission-denied'](https://github.com/fpco/cache-s3/tree/permission-denied) branch. If you need a prerelease (a downloadable binary) to confirm it, let me know I can create one fairly quickly

**Comment by wagdav** [comment] 2019-04-16 18:08
@lehins Thanks for the quick update, I'll test it tomorrow, first thing in the morning!

**Closed as completed** 2019-04-16 18:11 UTC

**Comment by lehins** [comment] 2019-04-16 18:12
@wagdav I was able to reproduce the error on AppVeyor and confirm that it is fixed now. I'll make a new release in a little bit. Reopen the issue if you find that the issue is still there in the upcoming cache-s3-0.1.9

**Comment by wagdav** [comment] 2019-04-17 06:39
@lehins  Thank you for the quick fix! I could also confirm that now it's working OK! :+1:
